### ISSUE TITLE
slh-dsa.py key generation issue

### ISSUE THREAD

**Issue by livebe01** [mjosaarinen/slh-dsa-py#1]
Hi,

I was looking at the kat directory, and I'm not sure if key generation is being done correctly?

I have the sphincsplus [consistent-based](https://github.com/sphincs/sphincsplus/tree/consistent-basew) branch installed and I've run PQCgenKAT_sign for sphincs-sha2-128f. I then hashed the resulting PQCsignKAT_64.rsp and verified its value against the value listed for sphincs-sha2-128f-robust at https://github.com/sphincs/sphincsplus/blob/consistent-basew/SHA256SUMS#L13C1-L13C90 and the values match.

Looking closer at PQCsignKAT_64.rsp for sphincs-sha2-128f, the values for count = 0 are (I omitted sm as it was so large):
> seed = 061550234D158C5EC95595FE04EF7A25767F2E24CC2BC479D09D86DC9ABCFDE7056A8C266F9EF97ED08541DBD2E1FFA1
mlen = 33
msg = D81C4D8D734FCBFBEADE3D3F8A039FAA2A2C9957E835AD55B22E75BF57BB556AC8
pk = B505D7CFAD1B497499323C8686325E473985E5A31E5B9A0457916C84320C2EA8
sk = 7C9935A0B07694AA0C6D10E4DB6B1ADD2FD81A25CCB148032DCD739936737F2DB505D7CFAD1B497499323C8686325E473985E5A31E5B9A0457916C84320C2EA8
smlen = 17121

The values calculated by your py implementation from https://github.com/mjosaarinen/slh-dsa-py/blob/main/kat/sphincs-sha2-128f-simple.rsp.1 are:
> seed = 061550234D158C5EC95595FE04EF7A25767F2E24CC2BC479D09D86DC9ABCFDE7056A8C266F9EF97ED08541DBD2E1FFA1
mlen = 33
msg = D81C4D8D734FCBFBEADE3D3F8A039FAA2A2C9957E835AD55B22E75BF57BB556AC8
pk = B505D7CFAD1B497499323C8686325E47FDF7400AB7A5D8C7ABA7350AC4092ADD
sk = 7C9935A0B07694AA0C6D10E4DB6B1ADD2FD81A25CCB148032DCD739936737F2DB505D7CFAD1B497499323C8686325E47FDF7400AB7A5D8C7ABA7350AC4092ADD
smlen = 17121

Notice that the last 32 characters of pk and sk differ.

Thanks,

Ben

**Comment by mjosaarinen** [comment]
> I have the sphincsplus [consistent-based](https://github.com/sphincs/sphincsplus/tree/consistent-basew) branch installed and I've run PQCgenKAT_sign for sphincs-sha2-128f. I then hashed the resulting PQCsignKAT_64.rsp and verified its value against the value listed for sphincs-sha2-128f-robust at https://github.com/sphincs/sphincsplus/blob/consistent-basew/SHA256SUMS#L13C1-L13C90 and the values match.

Hi,

Well, your sphincs-sha2-128f-**robust** is not a part of SLH-DSA and not supported by this implementation. Only the "simple" parameters are ( see the last paragraph of section 1.3 on page 2 of  https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.205.ipd.pdf )

If you look at one line down, you will see the hex value `664a19493058178ad7ebb65037183e69e79b1e27668142f6ce684db304aff59a  sphincs-sha2-128f-simple.rsp`  which matches with a line in in the `kat100-sha256.txt` file in this repo.

Cheers,
-markku
